kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{.Values.persistence.storageClass}}
provisioner: efs.csi.aws.com  # AWS EFS CSI 드라이버 프로비저너
parameters:
  provisioningMode: efs-ap
  fileSystemId: {{.Values.forever.efsId}}
  directoryPerms: "700"
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.persistence.existingClaim}}
  namespace: devops-tools
spec:
  storageClassName: {{.Values.persistence.storageClass}}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.persistence.size}}  # EFS는 용량 제한이 없지만 Kubernetes 요구사항 상 필요

