apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.persistence.existingClaim}}
  namespace: jenkins
spec:
  storageClassName: {{.Values.persistence.storageClass}}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.persistence.size}}  # EFS는 용량 제한이 없지만 Kubernetes 요구사항 상 필요

