apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-create-topics
  namespace: kafka
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      containers:
        - name: create-topics
          image: bitnami/kafka:latest
          command:
            - /bin/bash
            - -c
            - |
              kafka-topics.sh --create --if-not-exists --topic promotion_event --partitions 100 --replication-factor 1 --bootstrap-server kafka.kafka.svc.cluster.local:9092
              kafka-topics.sh --create --if-not-exists --topic promotion_result --partitions 100 --replication-factor 1 --bootstrap-server kafka.kafka.svc.cluster.local:9092
              kafka-topics.sh --create --if-not-exists --topic user_point --partitions 100 --replication-factor 1 --bootstrap-server kafka.kafka.svc.cluster.local:9092
              kafka-topics.sh --create --if-not-exists --topic forever_mysql_db_aurora.forever_mysql_db.outbox_event --partitions 100 --replication-factor 1 --bootstrap-server kafka.kafka.svc.cluster.local:9092
              kafka-topics.sh --create --if-not-exists --topic dbhistory.forever_mysql_db_aurora --partitions 1 --replication-factor 1 --bootstrap-server kafka.kafka.svc.cluster.local:9092
      restartPolicy: OnFailure
      serviceAccountName: kafka
