---
apiVersion: v1
kind: ConfigMap
metadata:
  name: all-user-once-each
data:
  tttest.js: |
    import http from 'k6/http';

    export const options = {
      vus: 30,
      iterations: 30, // 유저 수 만큼 반복
    };

    const users = [4, 5, 6, 7,8,9,10];

    export default function () {
      const userId = users[__ITER];
      const url = 'http://k8s-default-reactapp-dc89345727-5a550320895082ce.elb.ap-northeast-2.amazonaws.com/api/v1/event';

      const payload = JSON.stringify({
        userId: userId,
        eventId: 1,
      });

      const params = {
        headers: {
          'Content-Type': 'application/json',
        },
      };

      http.post(url, payload, params);
    }
---
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: my-k6-loadtest
spec:
  parallelism: 1
  script:
    configMap:
      name: all-user-once-each
      file: tttest.js
  arguments: ""
apiVersion: k6.io/v1alpha1

