apiVersion: v1
kind: ConfigMap
metadata:
  name: user1-burst
data:
  ttest.js: |
    import http from 'k6/http';

    export const options = {
      vus: 50,         
      duration: '5s', 
    };

    export default function () {
      const url = 'http://k8s-default-reactapp-dc89345727-5a550320895082ce.elb.ap-northeast-2.amazonaws.com/api/v1/event';

      const payload = JSON.stringify({
        userId: 1,
        eventId: 1,
      });

      const params = {
        headers: {
          'Content-Type': 'application/json',
        },
      };

      http.post(url, payload, params);
    }

