extraArgs:
  - --kafka.server=kafka.kafka.svc.cluster.local:9092

image:
  repository: danielqsj/kafka-exporter
  tag: v1.9.0
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

service:
  port: 9308
  portName: http
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "9308"
    prometheus.io/scrape: "true"

prometheus:
  serviceMonitor:
    enabled: true
    namespace: monitoring
    interval: 30s
    additionalLabels:
      release: kube-prometheus
