apiVersion: v1
kind: ConfigMap
metadata:
  name: single-run-50000aabb
data:
  single-run-50000aabb.js: |
    import http from 'k6/http';
    import { check, sleep } from 'k6';

    export let options = {
        stages: [
            { duration: '1m30s', target: 1000 },
            { duration: '1m30s', target: 3000 },
            { duration: '1m30s', target: 6000 },
            { duration: '1m30s', target: 10000 },
            { duration: '1m30s', target: 20000 },
            { duration: '1m30s', target: 30000 },
            { duration: '1m30s', target: 40000 },
            { duration: '1m30s', target: 50000 },
            { duration: '2m', target: 50000 },
            { duration: '1m', target: 0 }
        ],
    };

    const BASE_URL = 'http://k8s-default-reactapp-b81ff3f555-ead17ee6d6f665fb.elb.ap-northeast-2.amazonaws.com';

    export default function () {
        const userId = __VU.toString(); // 가상 유저 ID
        const price = 1000;

        const postRes = http.post(`${BASE_URL}/api/v1/point`, JSON.stringify({
            price: price,
            userId: userId,
        }), {
            headers: { 'Content-Type': 'application/json' },
        });

        check(postRes, {
            'POST status is 200': (r) => r.status === 200,
        });

        sleep(0.1); // 부하 완화
    }

---
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: loadtest-single-run-50000aabb
spec:
  parallelism: 1
  script:
    configMap:
      name: single-run-50000aabb
      file: single-run-50000aabb.js
  arguments: ""

