apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-stream-server
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/Team-ForeverYoung/infra-app
    path: us-bechart
    targetRevision: main
    helm:
      valueFiles:
        - values-custom.yaml
  destination:
    server: https://E8ED4150C72D6469FD7DBA74351E5671.gr7.us-east-1.eks.amazonaws.com
    namespace: app-us
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
