auth:
  enabled: false

controller:
  replicaCount: 4
  heapOpts: "-Xmx4096m -Xms4096m"
  resources:
    requests:
      cpu: 2
      memory: 4Gi
    limits:
      cpu: 4
      memory: 8Gi
image:
  registry: 911167924085.dkr.ecr.ap-northeast-2.amazonaws.com
  repository: temp2
  tag: 4.0.0-debian-12-r5
  pullPolicy: IfNotPresent


broker:
  persistence:
    enabled: false
  replicaCount: 4
  resources:
    requests:
      memory: 4Gi      # 최소 4Gi 이상으로 늘림
      cpu: 2           # 필요시 CPU도 늘림
    limits:
      memory: 8Gi      # 최대 8Gi 이상으로 늘림
      cpu: 4           # 필요시 CPU도 늘림
  heapOpts: -Xmx4096m -Xms4096m  # JVM 힙도 늘림 (메모리의 50~70% 권장)
controller:
  persistence:
    enabled: false
  replicaCount: 3

externalAccess:
  enabled: false

livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

metrics:
  kafka:
    enabled: false

listeners:
  ## @param listeners.client.name Name for the Kafka client listener
  ## @param listeners.client.containerPort Port for the Kafka client listener
  ## @param listeners.client.protocol Security protocol for the Kafka client listener. Allowed values are 'PLAINTEXT', 'SASL_PLAINTEXT', 'SASL_SSL' and 'SSL'
  ## @param listeners.client.sslClientAuth Optional. If SASL_SSL is enabled, configure mTLS TLS authentication type. If SSL protocol is enabled, overrides tls.authType for this listener. Allowed values are 'none', 'requested' and 'required'
  client:
    containerPort: 9092
    protocol: PLAINTEXT
