metrics:
  kafka:
    enabled: true

  jmx:
    enabled: true
    containerPorts:
      metrics: 5556
    kafkaJmxPort: 5555

    service:
      ports:
        metrics: 5556
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "5556"

    serviceMonitor:
      enabled: true
      interval: 30s
      scrapeTimeout: 10s

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

    whitelistObjectNames:
      - kafka.controller:*
      - kafka.server:*
      - java.lang:*
      - kafka.network:*
      - kafka.log:*

